# Generated by Django 4.2.6 on 2023-12-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0009_alter_match_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="number",
            field=models.IntegerField(null=True),
        ),
    ]
