# Generated by Django 4.2.8 on 2023-12-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0011_alter_team_options_team_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["datetime"], "verbose_name_plural": "matches"},
        ),
        migrations.AlterField(
            model_name="match",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_planner.league",
                verbose_name="Match belong to that League",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_planner.league",
                verbose_name="Match belong to that League",
            ),
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField(verbose_name="Start date of season")),
                ("end_date", models.DateField(verbose_name="End date of season")),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="league_planner.league",
                        verbose_name="Season belong to that League",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_planner.season",
                verbose_name="Match belong to that Season",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="league_planner.season",
                verbose_name="Team belong to that Season",
            ),
        ),
    ]
