# Generated by Django 4.2.8 on 2023-12-21 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0012_alter_match_options_alter_match_league_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="league_planner.season",
                verbose_name="Match belong to that Season",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="league_planner.season",
                verbose_name="Team belong to that Season",
            ),
        ),
    ]
