# Generated by Django 4.2.8 on 2023-12-21 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0013_alter_match_season_alter_team_season"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="league",
        ),
        migrations.RemoveField(
            model_name="team",
            name="league",
        ),
    ]
