# Generated by Django 4.2.8 on 2023-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0014_remove_match_league_remove_team_league"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="end_date",
            field=models.DateField(null=True, verbose_name="End date of season"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_date",
            field=models.DateField(null=True, verbose_name="Start date of season"),
        ),
    ]
