# Generated by Django 4.2.8 on 2023-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0015_alter_season_end_date_alter_season_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="points_per_draw",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Points per draw"),
        ),
        migrations.AddField(
            model_name="season",
            name="points_per_lose",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Points per lose"),
        ),
        migrations.AddField(
            model_name="season",
            name="points_per_win",
            field=models.PositiveSmallIntegerField(default=3, verbose_name="Points per win"),
        ),
    ]
