version: "3.8"
x-league-planner: &league-planner-config
  environment:
    - FLAVOR=localdev
  image: league-planner-dev
  build:
    context: ./
    args:
      - BUILD_COMMIT_SHA=localdev
  volumes:
    - "./:/code/"
  env_file:
    - .env


services:
  postgres:
    image: postgres:12.13-bullseye
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=league_planner

  django:
    <<: *league-planner-config
    command: >-
      bash -c "python ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    ports:
      - "8080:8000"
